// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://lebtkbjapflyomzorgzz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlYnRrYmphcGZseW9tem9yZ3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2NjE4MzUsImV4cCI6MjA0ODIzNzgzNX0.OPB_nnihsrSKVvSvcVi4JBF29NDAaW9ralSXBpCeM8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);